-- Catálogo ampliado de sitios anatómicos (idempotente por nombre UNIQUE)

INSERT INTO microlab.sitio_anatomico (nombre) VALUES
    ('Amígdalas'),
    ('Piel'),
    ('Tejido Blando'),
    ('Herida Quirúrgica'),
    ('Úlcera'),
    ('Absceso'),
    ('Quemadura de piel'),
    ('Catéter Venoso Central'),
    ('Catéter Urinario'),
    ('Punta de Catéter'),
    ('Sistema nervioso central'),
    ('Peritoneo'),
    ('Pleura'),
    ('Pericardio'),
    ('Médula Ósea'),
    ('Hueso'),
    ('Articulación'),
    ('Colon'),
    ('Recto'),
    ('Intestino Delgado'),
    ('Apéndice'),
    ('Hígado'),
    ('Vesícula Biliar'),
    ('Riñón'),
    ('Uréter'),
    ('Uretra'),
    ('Próstata'),
    ('Cérvix'),
    ('Vagina'),
    ('Endocérvix'),
    ('Oído'),
    ('Conjuntiva'),
    ('Cuero Cabelludo'),
    ('Lengua')
ON CONFLICT (nombre) DO NOTHING;
